import type { Metadata } from "next";

import { brand } from "@/lib/brand";

/**
 * Social sharing metadata for the confidential proposal pages under /propostas.
 *
 * Each proposal is shared with its client as a private link (WhatsApp, e-mail),
 * so the link preview has to look like the cover of the document itself — not
 * like the generic platform card from the root layout.
 *
 * Adding a new proposal means adding one entry to `proposalPages`: the route,
 * the metadata (title, description, canonical) and the Open Graph card image
 * are all derived from it. Nothing below is client-specific.
 *
 * Open Graph is for social scrapers; indexing is a separate concern. Every
 * proposal stays `noindex, nofollow` for search engines — see
 * `buildProposalMetadata` and the X-Robots-Tag rules in next.config.ts.
 */

/** Host under which proposals are shared with clients. Mirrors next.config.ts. */
export const PROPOSAL_CANONICAL_ORIGIN = "https://app.onebridgestalwart.com";

/** Route prefix for confidential proposal pages. */
export const PROPOSAL_ROUTE_PREFIX = "/propostas";

/** Brand lockup rendered on every generated share card. */
export const PROPOSAL_SHARE_LOGO_PATH = "public/logo.png";

export interface ProposalPage {
  /** URL segment under /propostas — the public share slug. */
  slug: string;
  /** Client identity, used as the headline of the share card. */
  clientName: string;
  /** Document title and og:title. */
  title: string;
  /** Meta description and og:description. */
  description: string;
  /** Small label above the client name on the share card. */
  eyebrow: string;
  /** One-line scope shown under the client name on the share card. */
  subtitle: string;
  /** Discreet jurisdiction marker at the foot of the share card. */
  jurisdiction: string;
  /** Static document embedded by the page. */
  documentPath: string;
  /** Accessible title for the embedded document. */
  documentTitle: string;
  /**
   * Absolute-from-root path to a hand-made card, when a proposal needs one.
   * Defaults to the card generated by /propostas/<slug>/og.png.
   */
  ogImagePath?: string;
}

export const proposalPages: readonly ProposalPage[] = [
  {
    slug: "familia-silva-8f4d2a",
    clientName: "Família Silva",
    title: `Proposta Comercial — Família Silva | ${brand.organizationName}`,
    description:
      "Proposta personalizada de estruturação societária, contábil e fiscal nos Estados Unidos.",
    eyebrow: "PROPOSTA COMERCIAL",
    subtitle: "Estruturação Societária, Contábil e Fiscal",
    jurisdiction: "ESTADOS UNIDOS",
    documentPath: "/proposal-assets/familia-silva-8f4d2a.html",
    documentTitle: "Proposta comercial da Família Silva"
  },
  {
    slug: "sit-international-backoffice",
    clientName: "SIT",
    title: `International Backoffice & Governance — SIT | ${brand.organizationName}`,
    description:
      "Coordenação, compliance e controle das estruturas da SIT nos Estados Unidos e no México.",
    eyebrow: "PROPOSTA PRELIMINAR",
    subtitle: "International Backoffice & Governance",
    jurisdiction: "ESTADOS UNIDOS + MÉXICO",
    documentPath: "/proposal-assets/sit-international-backoffice.html",
    documentTitle: "Proposta International Backoffice & Governance da SIT"
  }
];

export function getProposalPage(slug: string): ProposalPage | undefined {
  return proposalPages.find((page) => page.slug === slug);
}

/** Canonical, absolute URL of the proposal page. */
export function proposalPageUrl(page: ProposalPage): string {
  return `${PROPOSAL_CANONICAL_ORIGIN}${PROPOSAL_ROUTE_PREFIX}/${page.slug}`;
}

/** Absolute, https URL of the Open Graph card. Must resolve without a session. */
export function proposalOgImageUrl(page: ProposalPage): string {
  const imagePath = page.ogImagePath ?? `${PROPOSAL_ROUTE_PREFIX}/${page.slug}/og.png`;
  return `${PROPOSAL_CANONICAL_ORIGIN}${imagePath}`;
}

export const PROPOSAL_OG_IMAGE_SIZE = { width: 1200, height: 630 } as const;

/**
 * Full metadata for a proposal page: per-client Open Graph and Twitter cards,
 * canonical URL, and the unchanged noindex policy.
 */
export function buildProposalMetadata(page: ProposalPage): Metadata {
  const url = proposalPageUrl(page);
  const image = proposalOgImageUrl(page);

  return {
    metadataBase: new URL(PROPOSAL_CANONICAL_ORIGIN),
    // `absolute` keeps the internal platform name out of the client-facing title.
    title: { absolute: page.title },
    description: page.description,
    alternates: {
      canonical: url
    },
    robots: {
      index: false,
      follow: false,
      nocache: true,
      googleBot: {
        index: false,
        follow: false,
        noimageindex: true
      }
    },
    openGraph: {
      type: "website",
      title: page.title,
      description: page.description,
      url,
      siteName: brand.organizationName,
      locale: "pt_BR",
      images: [
        {
          url: image,
          width: PROPOSAL_OG_IMAGE_SIZE.width,
          height: PROPOSAL_OG_IMAGE_SIZE.height,
          type: "image/png",
          alt: page.title
        }
      ]
    },
    twitter: {
      card: "summary_large_image",
      title: page.title,
      description: page.description,
      images: [image]
    }
  };
}
